/*
 * RealEstateCore Core Module
 * The documentation below is automatically extracted from an <rdfs:comment> annotation on the ontology RealEstateCore Core Module:<br/><br/>*The REC core module collects the top-level classes and properties that span over or are reused within multiple REC modules.<br/><br/>Note that this module reuses certain classes, properties, and named individuals from other vocabularies, e.g., GeoSPARQL; the copyright conditions on those reused entities are stated in their respective rdfs:comments annotations.*
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Building;
import io.swagger.client.model.BuildingComponent;
import io.swagger.client.model.Context;
import io.swagger.client.model.Device;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * BuildingComponent
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-10-16T06:50:30.499Z[GMT]")
public class BuildingComponent {
  @SerializedName("@context")
  private Context _atContext = null;

  @SerializedName("@id")
  private String _atId = null;

  @SerializedName("@type")
  private String _atType = "BuildingComponent";

  @SerializedName("label")
  private String label = null;

  @SerializedName("containsMountedDevice")
  private List<Device> containsMountedDevice = null;

  @SerializedName("hasSubBuildingComponent")
  private List<BuildingComponent> hasSubBuildingComponent = null;

  @SerializedName("hasSuperBuildingComponent")
  private BuildingComponent hasSuperBuildingComponent = null;

  @SerializedName("isPartOfBuilding")
  private Building isPartOfBuilding = null;

  public BuildingComponent _atContext(Context _atContext) {
    this._atContext = _atContext;
    return this;
  }

   /**
   * Get _atContext
   * @return _atContext
  **/
  @Schema(description = "")
  public Context getAtContext() {
    return _atContext;
  }

  public void setAtContext(Context _atContext) {
    this._atContext = _atContext;
  }

  public BuildingComponent _atId(String _atId) {
    this._atId = _atId;
    return this;
  }

   /**
   * Get _atId
   * @return _atId
  **/
  @Schema(description = "")
  public String getAtId() {
    return _atId;
  }

  public void setAtId(String _atId) {
    this._atId = _atId;
  }

  public BuildingComponent _atType(String _atType) {
    this._atType = _atType;
    return this;
  }

   /**
   * Get _atType
   * @return _atType
  **/
  @Schema(description = "")
  public String getAtType() {
    return _atType;
  }

  public void setAtType(String _atType) {
    this._atType = _atType;
  }

  public BuildingComponent label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @Schema(description = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public BuildingComponent containsMountedDevice(List<Device> containsMountedDevice) {
    this.containsMountedDevice = containsMountedDevice;
    return this;
  }

  public BuildingComponent addContainsMountedDeviceItem(Device containsMountedDeviceItem) {
    if (this.containsMountedDevice == null) {
      this.containsMountedDevice = new ArrayList<Device>();
    }
    this.containsMountedDevice.add(containsMountedDeviceItem);
    return this;
  }

   /**
   * Get containsMountedDevice
   * @return containsMountedDevice
  **/
  @Schema(description = "")
  public List<Device> getContainsMountedDevice() {
    return containsMountedDevice;
  }

  public void setContainsMountedDevice(List<Device> containsMountedDevice) {
    this.containsMountedDevice = containsMountedDevice;
  }

  public BuildingComponent hasSubBuildingComponent(List<BuildingComponent> hasSubBuildingComponent) {
    this.hasSubBuildingComponent = hasSubBuildingComponent;
    return this;
  }

  public BuildingComponent addHasSubBuildingComponentItem(BuildingComponent hasSubBuildingComponentItem) {
    if (this.hasSubBuildingComponent == null) {
      this.hasSubBuildingComponent = new ArrayList<BuildingComponent>();
    }
    this.hasSubBuildingComponent.add(hasSubBuildingComponentItem);
    return this;
  }

   /**
   * Get hasSubBuildingComponent
   * @return hasSubBuildingComponent
  **/
  @Schema(description = "")
  public List<BuildingComponent> getHasSubBuildingComponent() {
    return hasSubBuildingComponent;
  }

  public void setHasSubBuildingComponent(List<BuildingComponent> hasSubBuildingComponent) {
    this.hasSubBuildingComponent = hasSubBuildingComponent;
  }

  public BuildingComponent hasSuperBuildingComponent(BuildingComponent hasSuperBuildingComponent) {
    this.hasSuperBuildingComponent = hasSuperBuildingComponent;
    return this;
  }

   /**
   * Get hasSuperBuildingComponent
   * @return hasSuperBuildingComponent
  **/
  @Schema(description = "")
  public BuildingComponent getHasSuperBuildingComponent() {
    return hasSuperBuildingComponent;
  }

  public void setHasSuperBuildingComponent(BuildingComponent hasSuperBuildingComponent) {
    this.hasSuperBuildingComponent = hasSuperBuildingComponent;
  }

  public BuildingComponent isPartOfBuilding(Building isPartOfBuilding) {
    this.isPartOfBuilding = isPartOfBuilding;
    return this;
  }

   /**
   * Get isPartOfBuilding
   * @return isPartOfBuilding
  **/
  @Schema(required = true, description = "")
  public Building getIsPartOfBuilding() {
    return isPartOfBuilding;
  }

  public void setIsPartOfBuilding(Building isPartOfBuilding) {
    this.isPartOfBuilding = isPartOfBuilding;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuildingComponent buildingComponent = (BuildingComponent) o;
    return Objects.equals(this._atContext, buildingComponent._atContext) &&
        Objects.equals(this._atId, buildingComponent._atId) &&
        Objects.equals(this._atType, buildingComponent._atType) &&
        Objects.equals(this.label, buildingComponent.label) &&
        Objects.equals(this.containsMountedDevice, buildingComponent.containsMountedDevice) &&
        Objects.equals(this.hasSubBuildingComponent, buildingComponent.hasSubBuildingComponent) &&
        Objects.equals(this.hasSuperBuildingComponent, buildingComponent.hasSuperBuildingComponent) &&
        Objects.equals(this.isPartOfBuilding, buildingComponent.isPartOfBuilding);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_atContext, _atId, _atType, label, containsMountedDevice, hasSubBuildingComponent, hasSuperBuildingComponent, isPartOfBuilding);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuildingComponent {\n");
    
    sb.append("    _atContext: ").append(toIndentedString(_atContext)).append("\n");
    sb.append("    _atId: ").append(toIndentedString(_atId)).append("\n");
    sb.append("    _atType: ").append(toIndentedString(_atType)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    containsMountedDevice: ").append(toIndentedString(containsMountedDevice)).append("\n");
    sb.append("    hasSubBuildingComponent: ").append(toIndentedString(hasSubBuildingComponent)).append("\n");
    sb.append("    hasSuperBuildingComponent: ").append(toIndentedString(hasSuperBuildingComponent)).append("\n");
    sb.append("    isPartOfBuilding: ").append(toIndentedString(isPartOfBuilding)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
