/*
 * RealEstateCore Core Module
 * The documentation below is automatically extracted from an <rdfs:comment> annotation on the ontology RealEstateCore Core Module:<br/><br/>*The REC core module collects the top-level classes and properties that span over or are reused within multiple REC modules.<br/><br/>Note that this module reuses certain classes, properties, and named individuals from other vocabularies, e.g., GeoSPARQL; the copyright conditions on those reused entities are stated in their respective rdfs:comments annotations.*
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Context
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-10-16T06:50:30.499Z[GMT]")
public class Context {
  @SerializedName("@vocab")
  private String _atVocab = "https://w3id.org/rec/core/";

  @SerializedName("@base")
  private String _atBase = null;

  @SerializedName("label")
  private String label = "http://www.w3.org/2000/01/rdf-schema#label";

  public Context _atVocab(String _atVocab) {
    this._atVocab = _atVocab;
    return this;
  }

   /**
   * Get _atVocab
   * @return _atVocab
  **/
  @Schema(required = true, description = "")
  public String getAtVocab() {
    return _atVocab;
  }

  public void setAtVocab(String _atVocab) {
    this._atVocab = _atVocab;
  }

  public Context _atBase(String _atBase) {
    this._atBase = _atBase;
    return this;
  }

   /**
   * Get _atBase
   * @return _atBase
  **/
  @Schema(required = true, description = "")
  public String getAtBase() {
    return _atBase;
  }

  public void setAtBase(String _atBase) {
    this._atBase = _atBase;
  }

  public Context label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @Schema(required = true, description = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Context context = (Context) o;
    return Objects.equals(this._atVocab, context._atVocab) &&
        Objects.equals(this._atBase, context._atBase) &&
        Objects.equals(this.label, context.label);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_atVocab, _atBase, label);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Context {\n");
    
    sb.append("    _atVocab: ").append(toIndentedString(_atVocab)).append("\n");
    sb.append("    _atBase: ").append(toIndentedString(_atBase)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
