/*
 * RealEstateCore Core Module
 * The documentation below is automatically extracted from an <rdfs:comment> annotation on the ontology RealEstateCore Core Module:<br/><br/>*The REC core module collects the top-level classes and properties that span over or are reused within multiple REC modules.<br/><br/>Note that this module reuses certain classes, properties, and named individuals from other vocabularies, e.g., GeoSPARQL; the copyright conditions on those reused entities are stated in their respective rdfs:comments annotations.*
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Context;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Geometry
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-10-16T06:50:30.499Z[GMT]")
public class Geometry {
  @SerializedName("@context")
  private Context _atContext = null;

  @SerializedName("@id")
  private String _atId = null;

  @SerializedName("@type")
  private String _atType = "Geometry";

  @SerializedName("label")
  private String label = null;

  @SerializedName("asGML")
  private List<String> asGML = null;

  @SerializedName("asWKT")
  private List<String> asWKT = null;

  @SerializedName("hasSerialization")
  private List<String> hasSerialization = null;

  public Geometry _atContext(Context _atContext) {
    this._atContext = _atContext;
    return this;
  }

   /**
   * Get _atContext
   * @return _atContext
  **/
  @Schema(description = "")
  public Context getAtContext() {
    return _atContext;
  }

  public void setAtContext(Context _atContext) {
    this._atContext = _atContext;
  }

  public Geometry _atId(String _atId) {
    this._atId = _atId;
    return this;
  }

   /**
   * Get _atId
   * @return _atId
  **/
  @Schema(description = "")
  public String getAtId() {
    return _atId;
  }

  public void setAtId(String _atId) {
    this._atId = _atId;
  }

  public Geometry _atType(String _atType) {
    this._atType = _atType;
    return this;
  }

   /**
   * Get _atType
   * @return _atType
  **/
  @Schema(description = "")
  public String getAtType() {
    return _atType;
  }

  public void setAtType(String _atType) {
    this._atType = _atType;
  }

  public Geometry label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @Schema(description = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public Geometry asGML(List<String> asGML) {
    this.asGML = asGML;
    return this;
  }

  public Geometry addAsGMLItem(String asGMLItem) {
    if (this.asGML == null) {
      this.asGML = new ArrayList<String>();
    }
    this.asGML.add(asGMLItem);
    return this;
  }

   /**
   * Get asGML
   * @return asGML
  **/
  @Schema(description = "")
  public List<String> getAsGML() {
    return asGML;
  }

  public void setAsGML(List<String> asGML) {
    this.asGML = asGML;
  }

  public Geometry asWKT(List<String> asWKT) {
    this.asWKT = asWKT;
    return this;
  }

  public Geometry addAsWKTItem(String asWKTItem) {
    if (this.asWKT == null) {
      this.asWKT = new ArrayList<String>();
    }
    this.asWKT.add(asWKTItem);
    return this;
  }

   /**
   * Get asWKT
   * @return asWKT
  **/
  @Schema(description = "")
  public List<String> getAsWKT() {
    return asWKT;
  }

  public void setAsWKT(List<String> asWKT) {
    this.asWKT = asWKT;
  }

  public Geometry hasSerialization(List<String> hasSerialization) {
    this.hasSerialization = hasSerialization;
    return this;
  }

  public Geometry addHasSerializationItem(String hasSerializationItem) {
    if (this.hasSerialization == null) {
      this.hasSerialization = new ArrayList<String>();
    }
    this.hasSerialization.add(hasSerializationItem);
    return this;
  }

   /**
   * Get hasSerialization
   * @return hasSerialization
  **/
  @Schema(description = "")
  public List<String> getHasSerialization() {
    return hasSerialization;
  }

  public void setHasSerialization(List<String> hasSerialization) {
    this.hasSerialization = hasSerialization;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Geometry geometry = (Geometry) o;
    return Objects.equals(this._atContext, geometry._atContext) &&
        Objects.equals(this._atId, geometry._atId) &&
        Objects.equals(this._atType, geometry._atType) &&
        Objects.equals(this.label, geometry.label) &&
        Objects.equals(this.asGML, geometry.asGML) &&
        Objects.equals(this.asWKT, geometry.asWKT) &&
        Objects.equals(this.hasSerialization, geometry.hasSerialization);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_atContext, _atId, _atType, label, asGML, asWKT, hasSerialization);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Geometry {\n");
    
    sb.append("    _atContext: ").append(toIndentedString(_atContext)).append("\n");
    sb.append("    _atId: ").append(toIndentedString(_atId)).append("\n");
    sb.append("    _atType: ").append(toIndentedString(_atType)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    asGML: ").append(toIndentedString(asGML)).append("\n");
    sb.append("    asWKT: ").append(toIndentedString(asWKT)).append("\n");
    sb.append("    hasSerialization: ").append(toIndentedString(hasSerialization)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
